---

- name: grafana-install-prerequisites | Install Prerequisites
  apt: name="apt-transport-https"

- name: grafana-install | Add debian repository pt. 1
  apt_key: url='{{grafana_apt_key}}' id=D59097AB

- name: grafana-install | Add debian repository pt. 2
  apt_repository: repo='{{grafana_apt_repository}}'

- set_fact: grafana_release='grafana={{grafana_version}}'

- name: grafana-install | Install Grafana Release
  apt: name="{{grafana_release}}"
  when: grafana_version != "latest"
  notify:
    - grafana restart

- name: grafana-install | Install Grafana Latest
  apt: name="grafana"
  when: grafana_version == "latest"
  notify:
  - grafana restart
